name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/node
    steps:
      - uses: actions/checkout@v4  # Dernière version

      - name: Use Node.js 16
        uses: actions/setup-node@v4  # Dernière version
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Upload coverage
        uses: actions/upload-artifact@v4  # Dernière version
        with:
          name: coverage-node
          path: packages/node/coverage