name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/node
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      # Utiliser un SHA spécifique pour l'action upload-artifact
      - name: Upload coverage
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: coverage-node
          path: packages/node/coverage